/**
 * Icon manifest. Edit this file to add/remove icons.
 * Run `npm run gen:icons` to regenerate per-icon modules + bundles.
 *
 * Icon kinds:
 *   - 'lucide'        — from lucide-react (use `name` as it's exported)
 *   - 'simple-icons'  — brand logos from simple-icons (use `name` as `siXxx`)
 *   - 'svg'           — raw SVG file in src/assets/icons/<path>
 *   - 'tsx'           — custom React component in src/assets/icons/<path>
 */
import type { Manifest } from './scripts/types';

export const manifest: Manifest = {
  packs: {
    'tag-icons': {
      icons: [
        // ── simple-icons (brand logos) ──
        { key: 'airbnb', kind: 'simple-icons', name: 'siAirbnb' },
        { key: 'apple', kind: 'simple-icons', name: 'siApple' },
        { key: 'google', kind: 'simple-icons', name: 'siGoogle' },
        { key: 'googlepay', kind: 'simple-icons', name: 'siGooglepay' },
        { key: 'netflix', kind: 'simple-icons', name: 'siNetflix' },
        { key: 'paytm', kind: 'simple-icons', name: 'siPaytm' },
        { key: 'phonepe', kind: 'simple-icons', name: 'siPhonepe' },
        { key: 'spotify', kind: 'simple-icons', name: 'siSpotify' },
        { key: 'swiggy', kind: 'simple-icons', name: 'siSwiggy' },
        { key: 'uber', kind: 'simple-icons', name: 'siUber' },
        { key: 'youtube', kind: 'simple-icons', name: 'siYoutube' },
        { key: 'zomato', kind: 'simple-icons', name: 'siZomato' },

        // ── svg (custom SVG assets) ──
        { key: 'amazon-pay', kind: 'svg', path: 'tags/amazon-pay.svg' },
        { key: 'amazon-prime-video', kind: 'svg', path: 'tags/amazon-prime-video.svg' },
        { key: 'blinkit', kind: 'svg', path: 'tags/blinkit.svg' },
        { key: 'bumble', kind: 'svg', path: 'tags/bumble.svg' },
        { key: 'cred', kind: 'svg', path: 'tags/cred.svg' },
        { key: 'cricket', kind: 'svg', path: 'tags/cricket.svg' },
        { key: 'district', kind: 'svg', path: 'tags/district.svg' },
        { key: 'eazydiner', kind: 'svg', path: 'tags/eazydiner.svg' },
        { key: 'fastag', kind: 'svg', path: 'tags/fastag.svg' },
        { key: 'father', kind: 'svg', path: 'tags/father.svg' },
        { key: 'football', kind: 'svg', path: 'tags/football.svg' },
        { key: 'lazypay', kind: 'svg', path: 'tags/lazypay.svg' },
        { key: 'mother', kind: 'svg', path: 'tags/mother.svg' },
        { key: 'namma-yatri', kind: 'svg', path: 'tags/namma-yatri.svg' },
        { key: 'nps', kind: 'svg', path: 'tags/nps.svg' },
        { key: 'ola', kind: 'svg', path: 'tags/ola.svg' },
        { key: 'ppf', kind: 'svg', path: 'tags/ppf.svg' },
        { key: 'rapido', kind: 'svg', path: 'tags/rapido.svg' },
        { key: 'simpl', kind: 'svg', path: 'tags/simpl.svg' },
        { key: 'slice', kind: 'svg', path: 'tags/slice.svg' },
        { key: 'upi', kind: 'svg', path: 'tags/upi.svg' },
        { key: 'zepto', kind: 'svg', path: 'tags/zepto.svg' },

        // ── tsx (custom React components using createLucideIcon) ──
        { key: 'auto', kind: 'tsx', path: 'tags/auto', name: 'AutoIcon' },
        { key: 'bowling', kind: 'tsx', path: 'tags/bowling', name: 'BowlingIcon' },
        { key: 'brownbag', kind: 'tsx', path: 'tags/brownbag', name: 'BrownBagIcon' },
        { key: 'gas', kind: 'tsx', path: 'tags/gas', name: 'GasIcon' },
        { key: 'goldbar', kind: 'tsx', path: 'tags/goldbar', name: 'GoldbarIcon' },
        { key: 'makeup', kind: 'tsx', path: 'tags/makeup', name: 'MakeupIcon' },
        { key: 'sewing', kind: 'tsx', path: 'tags/sewing', name: 'SewingIcon' },
        { key: 'shuttlecock', kind: 'tsx', path: 'tags/shuttlecock', name: 'ShuttlecockIcon' },
        { key: 'tiffin', kind: 'tsx', path: 'tags/tiffin', name: 'TiffinIcon' },
        { key: 'tooth', kind: 'tsx', path: 'tags/tooth', name: 'ToothIcon' },
        { key: 'whistle', kind: 'tsx', path: 'tags/whistle', name: 'WhistleIcon' },

        // ── lucide-react ──
        { key: 'app-window', kind: 'lucide', name: 'AppWindowIcon' },
        { key: 'armchair', kind: 'lucide', name: 'ArmchairIcon' },
        { key: 'arrow-left-right', kind: 'lucide', name: 'ArrowLeftRightIcon' },
        { key: 'backpack', kind: 'lucide', name: 'BackpackIcon' },
        { key: 'badge-indian-rupee', kind: 'lucide', name: 'BadgeIndianRupeeIcon' },
        { key: 'badge-question-mark', kind: 'lucide', name: 'BadgeQuestionMarkIcon' },
        { key: 'banana', kind: 'lucide', name: 'BananaIcon' },
        { key: 'banknote-arrow-down', kind: 'lucide', name: 'BanknoteArrowDownIcon' },
        { key: 'banknote-arrow-up', kind: 'lucide', name: 'BanknoteArrowUpIcon' },
        { key: 'battery-charging', kind: 'lucide', name: 'BatteryChargingIcon' },
        { key: 'bed', kind: 'lucide', name: 'BedIcon' },
        { key: 'beer', kind: 'lucide', name: 'BeerIcon' },
        { key: 'biceps-flexed', kind: 'lucide', name: 'BicepsFlexedIcon' },
        { key: 'bike-fast', kind: 'lucide', name: 'BikeIcon' },
        { key: 'bitcoin', kind: 'lucide', name: 'BitcoinIcon' },
        { key: 'book-heart', kind: 'lucide', name: 'BookHeartIcon' },
        { key: 'bookmark-x', kind: 'lucide', name: 'BookmarkXIcon' },
        { key: 'brick-wall-shield', kind: 'lucide', name: 'BrickWallShieldIcon' },
        { key: 'briefcase-business', kind: 'lucide', name: 'BriefcaseBusinessIcon' },
        { key: 'brush-cleaning', kind: 'lucide', name: 'BrushCleaningIcon' },
        { key: 'building', kind: 'lucide', name: 'BuildingIcon' },
        { key: 'bus', kind: 'lucide', name: 'BusIcon' },
        { key: 'cable', kind: 'lucide', name: 'CableIcon' },
        { key: 'calendar', kind: 'lucide', name: 'CalendarIcon' },
        { key: 'calendar-days', kind: 'lucide', name: 'CalendarDaysIcon' },
        { key: 'calendar-sync', kind: 'lucide', name: 'CalendarSyncIcon' },
        { key: 'camera', kind: 'lucide', name: 'CameraIcon' },
        { key: 'car', kind: 'lucide', name: 'CarIcon' },
        { key: 'car-front', kind: 'lucide', name: 'CarFrontIcon' },
        { key: 'car-taxi-front', kind: 'lucide', name: 'CarTaxiFrontIcon' },
        { key: 'carrot', kind: 'lucide', name: 'CarrotIcon' },
        { key: 'chart-candlestick', kind: 'lucide', name: 'ChartCandlestickIcon' },
        { key: 'chef-hat', kind: 'lucide', name: 'ChefHatIcon' },
        { key: 'cigarette', kind: 'lucide', name: 'CigaretteIcon' },
        { key: 'circle-dollar-sign', kind: 'lucide', name: 'CircleDollarSignIcon' },
        { key: 'circle-dot-dashed', kind: 'lucide', name: 'CircleDotDashedIcon' },
        { key: 'circle-parking', kind: 'lucide', name: 'CircleParkingIcon' },
        { key: 'clapperboard', kind: 'lucide', name: 'ClapperboardIcon' },
        { key: 'coffee', kind: 'lucide', name: 'CoffeeIcon' },
        { key: 'coins', kind: 'lucide', name: 'CoinsIcon' },
        { key: 'construction', kind: 'lucide', name: 'ConstructionIcon' },
        { key: 'cookie', kind: 'lucide', name: 'CookieIcon' },
        { key: 'corner-down-left', kind: 'lucide', name: 'CornerDownLeftIcon' },
        { key: 'credit-card', kind: 'lucide', name: 'CreditCardIcon' },
        { key: 'croissant', kind: 'lucide', name: 'CroissantIcon' },
        { key: 'cross', kind: 'lucide', name: 'CrossIcon' },
        { key: 'diamond-percent', kind: 'lucide', name: 'DiamondPercentIcon' },
        { key: 'droplet', kind: 'lucide', name: 'DropletIcon' },
        { key: 'drumstick', kind: 'lucide', name: 'DrumstickIcon' },
        { key: 'dumbbell', kind: 'lucide', name: 'DumbbellIcon' },
        { key: 'eye-closed', kind: 'lucide', name: 'EyeClosedIcon' },
        { key: 'flame', kind: 'lucide', name: 'FlameIcon' },
        { key: 'footprints', kind: 'lucide', name: 'FootprintsIcon' },
        { key: 'fuel', kind: 'lucide', name: 'FuelIcon' },
        { key: 'gamepad-2', kind: 'lucide', name: 'Gamepad2Icon' },
        { key: 'gem', kind: 'lucide', name: 'GemIcon' },
        { key: 'gift', kind: 'lucide', name: 'GiftIcon' },
        { key: 'glasses', kind: 'lucide', name: 'GlassesIcon' },
        { key: 'glass-water', kind: 'lucide', name: 'GlassWaterIcon' },
        { key: 'graduation-cap', kind: 'lucide', name: 'GraduationCapIcon' },
        { key: 'grape', kind: 'lucide', name: 'GrapeIcon' },
        { key: 'hamburger', kind: 'lucide', name: 'HamburgerIcon' },
        { key: 'hammer', kind: 'lucide', name: 'HammerIcon' },
        { key: 'hand-coins', kind: 'lucide', name: 'HandCoinsIcon' },
        { key: 'hand-helping', kind: 'lucide', name: 'HandHelpingIcon' },
        { key: 'hand-platter', kind: 'lucide', name: 'HandPlatterIcon' },
        { key: 'handshake', kind: 'lucide', name: 'HandshakeIcon' },
        { key: 'heart', kind: 'lucide', name: 'HeartIcon' },
        { key: 'heart-handshake', kind: 'lucide', name: 'HeartHandshakeIcon' },
        { key: 'heart-plus', kind: 'lucide', name: 'HeartPlusIcon' },
        { key: 'hospital', kind: 'lucide', name: 'HospitalIcon' },
        { key: 'house', kind: 'lucide', name: 'HouseIcon' },
        { key: 'house-heart', kind: 'lucide', name: 'HouseHeartIcon' },
        { key: 'ice-cream-bowl', kind: 'lucide', name: 'IceCreamBowlIcon' },
        { key: 'ice-cream-cone', kind: 'lucide', name: 'IceCreamConeIcon' },
        { key: 'lamp', kind: 'lucide', name: 'LampIcon' },
        { key: 'landmark', kind: 'lucide', name: 'LandmarkIcon' },
        { key: 'laptop', kind: 'lucide', name: 'LaptopIcon' },
        { key: 'library-big', kind: 'lucide', name: 'LibraryBigIcon' },
        { key: 'mic', kind: 'lucide', name: 'MicIcon' },
        { key: 'milk', kind: 'lucide', name: 'MilkIcon' },
        { key: 'monitor-play', kind: 'lucide', name: 'MonitorPlayIcon' },
        { key: 'newspaper', kind: 'lucide', name: 'NewspaperIcon' },
        { key: 'package', kind: 'lucide', name: 'PackageIcon' },
        { key: 'paint-roller', kind: 'lucide', name: 'PaintRollerIcon' },
        { key: 'palette', kind: 'lucide', name: 'PaletteIcon' },
        { key: 'party-popper', kind: 'lucide', name: 'PartyPopperIcon' },
        { key: 'paw-print', kind: 'lucide', name: 'PawPrintIcon' },
        { key: 'pencil-ruler', kind: 'lucide', name: 'PencilRulerIcon' },
        { key: 'piggy-bank', kind: 'lucide', name: 'PiggyBankIcon' },
        { key: 'pill', kind: 'lucide', name: 'PillIcon' },
        { key: 'pill-bottle', kind: 'lucide', name: 'PillBottleIcon' },
        { key: 'pizza', kind: 'lucide', name: 'PizzaIcon' },
        { key: 'plane', kind: 'lucide', name: 'PlaneIcon' },
        { key: 'printer', kind: 'lucide', name: 'PrinterIcon' },
        { key: 'receipt-indian-rupee', kind: 'lucide', name: 'ReceiptIndianRupeeIcon' },
        { key: 'receipt-text', kind: 'lucide', name: 'ReceiptTextIcon' },
        { key: 'rose', kind: 'lucide', name: 'RoseIcon' },
        { key: 'rotate-ccw', kind: 'lucide', name: 'RotateCcwIcon' },
        { key: 'salad', kind: 'lucide', name: 'SaladIcon' },
        { key: 'sandwich', kind: 'lucide', name: 'SandwichIcon' },
        { key: 'satellite-dish', kind: 'lucide', name: 'SatelliteDishIcon' },
        { key: 'scale', kind: 'lucide', name: 'ScaleIcon' },
        { key: 'scissors', kind: 'lucide', name: 'ScissorsIcon' },
        { key: 'shield-user', kind: 'lucide', name: 'ShieldUserIcon' },
        { key: 'shirt', kind: 'lucide', name: 'ShirtIcon' },
        { key: 'shopping-bag', kind: 'lucide', name: 'ShoppingBagIcon' },
        { key: 'shopping-basket', kind: 'lucide', name: 'ShoppingBasketIcon' },
        { key: 'shopping-cart', kind: 'lucide', name: 'ShoppingCartIcon' },
        { key: 'sofa', kind: 'lucide', name: 'SofaIcon' },
        { key: 'soup', kind: 'lucide', name: 'SoupIcon' },
        { key: 'sparkles', kind: 'lucide', name: 'SparklesIcon' },
        { key: 'sprout', kind: 'lucide', name: 'SproutIcon' },
        { key: 'stamp', kind: 'lucide', name: 'StampIcon' },
        { key: 'stethoscope', kind: 'lucide', name: 'StethoscopeIcon' },
        { key: 'syringe', kind: 'lucide', name: 'SyringeIcon' },
        { key: 'tablet-smartphone', kind: 'lucide', name: 'TabletSmartphoneIcon' },
        { key: 'tent', kind: 'lucide', name: 'TentIcon' },
        { key: 'tent-tree', kind: 'lucide', name: 'TentTreeIcon' },
        { key: 'tickets', kind: 'lucide', name: 'TicketsIcon' },
        { key: 'toy-brick', kind: 'lucide', name: 'ToyBrickIcon' },
        { key: 'train-front', kind: 'lucide', name: 'TrainFrontIcon' },
        { key: 'train-track', kind: 'lucide', name: 'TrainTrackIcon' },
        { key: 'trending-up-down', kind: 'lucide', name: 'TrendingUpDownIcon' },
        { key: 'truck', kind: 'lucide', name: 'TruckIcon' },
        { key: 'user', kind: 'lucide', name: 'UserIcon' },
        { key: 'users', kind: 'lucide', name: 'UsersIcon' },
        { key: 'user-star', kind: 'lucide', name: 'UserStarIcon' },
        { key: 'utensils', kind: 'lucide', name: 'UtensilsIcon' },
        { key: 'vault', kind: 'lucide', name: 'VaultIcon' },
        { key: 'wallet', kind: 'lucide', name: 'WalletIcon' },
        { key: 'wand-sparkles', kind: 'lucide', name: 'WandSparklesIcon' },
        { key: 'washing-machine', kind: 'lucide', name: 'WashingMachineIcon' },
        { key: 'wheat', kind: 'lucide', name: 'WheatIcon' },
        { key: 'wifi', kind: 'lucide', name: 'WifiIcon' },
        { key: 'wine', kind: 'lucide', name: 'WineIcon' },
        { key: 'wrench', kind: 'lucide', name: 'WrenchIcon' },
        { key: 'zap', kind: 'lucide', name: 'ZapIcon' },
      ],
    },
    'currency-icons': {
      icons: [
        { key: 'indian-rupee', kind: 'lucide', name: 'IndianRupeeIcon' },
        { key: 'dollar-sign', kind: 'lucide', name: 'DollarSignIcon' },
        { key: 'euro', kind: 'lucide', name: 'EuroIcon' },
        { key: 'pound-sterling', kind: 'lucide', name: 'PoundSterlingIcon' },
        { key: 'japanese-yen', kind: 'lucide', name: 'JapaneseYenIcon' },
        { key: 'georgian-lari', kind: 'lucide', name: 'GeorgianLariIcon' },
        { key: 'philippine-peso', kind: 'lucide', name: 'PhilippinePesoIcon' },
        { key: 'russian-ruble', kind: 'lucide', name: 'RussianRubleIcon' },
        { key: 'saudi-riyal', kind: 'lucide', name: 'SaudiRiyalIcon' },
        { key: 'swiss-franc', kind: 'lucide', name: 'SwissFrancIcon' },
        { key: 'turkish-lira', kind: 'lucide', name: 'TurkishLiraIcon' },
      ],
    },
    // Shared chrome — navbar pills, theme switcher, sync status, tenants
    // page actions, and cross-component affordances. Loaded eagerly.
    common: {
      icons: [
        { key: 'arrow-left-right', kind: 'lucide', name: 'ArrowLeftRightIcon' },
        { key: 'bolt', kind: 'lucide', name: 'BoltIcon' },
        { key: 'calendar', kind: 'lucide', name: 'CalendarIcon' },
        { key: 'chevron-down', kind: 'lucide', name: 'ChevronDownIcon' },
        { key: 'circle-dashed', kind: 'lucide', name: 'CircleDashedIcon' },
        { key: 'cloud-check', kind: 'lucide', name: 'CloudCheckIcon' },
        { key: 'ellipsis-vertical', kind: 'lucide', name: 'EllipsisVerticalIcon' },
        { key: 'home', kind: 'lucide', name: 'HouseIcon' },
        { key: 'log-out', kind: 'lucide', name: 'LogOutIcon' },
        { key: 'monitor', kind: 'lucide', name: 'MonitorIcon' },
        { key: 'moon', kind: 'lucide', name: 'MoonIcon' },
        { key: 'refresh-cw', kind: 'lucide', name: 'RefreshCwIcon' },
        { key: 'sun', kind: 'lucide', name: 'SunIcon' },
        { key: 'trash-2', kind: 'lucide', name: 'Trash2Icon' },
        { key: 'user', kind: 'lucide', name: 'UserIcon' },
        { key: 'x', kind: 'lucide', name: 'XIcon' },
      ],
    },
  },
};
